// nlpTrainingData.js - Training Data for NLP Model
// This file contains all training data for future model versions
// Only loaded when explicitly training the model

// Comprehensive training data for intent recognition
export const trainingData = [
    // Project Creation Intents
    { text: 'create a new project', intent: 'project.create' },
    { text: 'start a new project', intent: 'project.create' },
    { text: 'begin project', intent: 'project.create' },
    { text: 'create project', intent: 'project.create' },
    { text: 'i want to start a project', intent: 'project.create' },
    { text: 'let\'s create a project', intent: 'project.create' },
    { text: 'new project', intent: 'project.create' },
    { text: 'i need a project plan', intent: 'project.create' },
    { text: 'project planning', intent: 'project.create' },
    { text: 'help me plan a project', intent: 'project.create' },
    
    // Scope Definition Intents
    { text: 'i want a project plan for a new hardware store', intent: 'scope.define' },
    { text: 'build a mobile app', intent: 'scope.define' },
    { text: 'create a website', intent: 'scope.define' },
    { text: 'launch a business', intent: 'scope.define' },
    { text: 'organize an event', intent: 'scope.define' },
    { text: 'develop software', intent: 'scope.define' },
    { text: 'marketing campaign', intent: 'scope.define' },
    { text: 'product launch', intent: 'scope.define' },
    { text: 'renovation project', intent: 'scope.define' },
    { text: 'research project', intent: 'scope.define' },
    
    // Budget Intents
    { text: 'set budget to 10000', intent: 'budget.set' },
    { text: 'update budget', intent: 'budget.set' },
    { text: 'change budget', intent: 'budget.set' },
    { text: 'modify budget', intent: 'budget.set' },
    { text: 'budget is 5000', intent: 'budget.set' },
    { text: 'i have 20000 dollars', intent: 'budget.set' },
    { text: 'cost around 15000', intent: 'budget.set' },
    { text: 'spending limit 8000', intent: 'budget.set' },
    { text: 'budget of 25000', intent: 'budget.set' },
    { text: 'can spend up to 30000', intent: 'budget.set' },
    
    // Timeline Intents
    { text: 'need it done in 3 months', intent: 'timeline.set' },
    { text: 'deadline is december', intent: 'timeline.set' },
    { text: 'due in 6 weeks', intent: 'timeline.set' },
    { text: 'finish by march', intent: 'timeline.set' },
    { text: '2 month timeline', intent: 'timeline.set' },
    { text: 'urgent deadline', intent: 'timeline.set' },
    { text: 'no rush on this', intent: 'timeline.set' },
    { text: 'flexible timeline', intent: 'timeline.set' },
    { text: 'timeline of 1 year', intent: 'timeline.set' },
    { text: 'complete by q2', intent: 'timeline.set' },
    
    // Task Management Intents
    { text: 'add tasks to my project', intent: 'tasks.create' },
    { text: 'create tasks', intent: 'tasks.create' },
    { text: 'add new tasks', intent: 'tasks.create' },
    { text: 'create new tasks', intent: 'tasks.create' },
    { text: 'list the tasks', intent: 'tasks.list' },
    { text: 'show me tasks', intent: 'tasks.list' },
    { text: 'what tasks do i have', intent: 'tasks.list' },
    { text: 'mark task complete', intent: 'tasks.complete' },
    { text: 'task is done', intent: 'tasks.complete' },
    { text: 'finished that task', intent: 'tasks.complete' },
    
    // Deliverables Intents
    { text: 'deliverables include app and website', intent: 'deliverables.define' },
    { text: 'need to produce reports', intent: 'deliverables.define' },
    { text: 'final deliverable is presentation', intent: 'deliverables.define' },
    { text: 'main output is prototype', intent: 'deliverables.define' },
    { text: 'deliver software package', intent: 'deliverables.define' },
    { text: 'create documentation', intent: 'deliverables.define' },
    { text: 'build mobile app', intent: 'deliverables.define' },
    { text: 'develop api', intent: 'deliverables.define' },
    { text: 'design mockups', intent: 'deliverables.define' },
    { text: 'write user manual', intent: 'deliverables.define' },
    
    // Dependencies Intents
    { text: 'depends on user research', intent: 'dependencies.define' },
    { text: 'need design approval first', intent: 'dependencies.define' },
    { text: 'waiting for budget approval', intent: 'dependencies.define' },
    { text: 'blocked by legal review', intent: 'dependencies.define' },
    { text: 'requires third party api', intent: 'dependencies.define' },
    { text: 'need external resources', intent: 'dependencies.define' },
    { text: 'depends on client feedback', intent: 'dependencies.define' },
    { text: 'waiting for materials', intent: 'dependencies.define' },
    { text: 'requires vendor approval', intent: 'dependencies.define' },
    { text: 'blocked by technical issues', intent: 'dependencies.define' },
    
    // Response Patterns
    { text: 'yes that looks good', intent: 'response.positive' },
    { text: 'yes', intent: 'response.positive' },
    { text: 'good', intent: 'response.positive' },
    { text: 'approve', intent: 'response.positive' },
    { text: 'confirm', intent: 'response.positive' },
    { text: 'correct', intent: 'response.positive' },
    { text: 'perfect', intent: 'response.positive' },
    { text: 'exactly', intent: 'response.positive' },
    { text: 'sounds good', intent: 'response.positive' },
    { text: 'looks good', intent: 'response.positive' },
    { text: 'that works', intent: 'response.positive' },
    { text: 'agreed', intent: 'response.positive' },
    
    { text: 'no change it', intent: 'response.negative' },
    { text: 'no', intent: 'response.negative' },
    { text: 'cancel', intent: 'response.negative' },
    { text: 'reject', intent: 'response.negative' },
    { text: 'wrong', intent: 'response.negative' },
    { text: 'incorrect', intent: 'response.negative' },
    { text: 'not right', intent: 'response.negative' },
    { text: 'that\'s not what i meant', intent: 'response.negative' },
    { text: 'different approach', intent: 'response.negative' },
    { text: 'try again', intent: 'response.negative' },
    { text: 'redo that', intent: 'response.negative' },
    { text: 'start over', intent: 'response.negative' },
    
    // Clarification Intents
    { text: 'can you explain more', intent: 'general.clarify' },
    { text: 'what do you mean', intent: 'general.clarify' },
    { text: 'i don\'t understand', intent: 'general.clarify' },
    { text: 'need more details', intent: 'general.clarify' },
    { text: 'explain that', intent: 'general.clarify' },
    { text: 'clarify please', intent: 'general.clarify' },
    { text: 'more information', intent: 'general.clarify' },
    { text: 'give me details', intent: 'general.clarify' },
    { text: 'elaborate', intent: 'general.clarify' },
    { text: 'can you be more specific', intent: 'general.clarify' },
    
    // Additional Scope Definition Examples (20 more)
    { text: 'we need to create a mobile app for iOS and Android', intent: 'scope.define' },
    { text: 'i want to build an e-commerce website', intent: 'scope.define' },
    { text: 'planning a marketing campaign for product launch', intent: 'scope.define' },
    { text: 'need to organize a corporate event', intent: 'scope.define' },
    { text: 'want to develop a web application', intent: 'scope.define' },
    { text: 'creating a new business from scratch', intent: 'scope.define' },
    { text: 'planning a home renovation project', intent: 'scope.define' },
    { text: 'need to launch a new product line', intent: 'scope.define' },
    { text: 'want to start a consulting business', intent: 'scope.define' },
    { text: 'planning a software development project', intent: 'scope.define' },
    { text: 'need to create a brand identity', intent: 'scope.define' },
    { text: 'want to build a social media platform', intent: 'scope.define' },
    { text: 'planning a data migration project', intent: 'scope.define' },
    { text: 'need to develop a mobile game', intent: 'scope.define' },
    { text: 'want to create an online course', intent: 'scope.define' },
    { text: 'planning a digital transformation', intent: 'scope.define' },
    { text: 'need to build a customer portal', intent: 'scope.define' },
    { text: 'want to launch a podcast', intent: 'scope.define' },
    { text: 'planning a content marketing strategy', intent: 'scope.define' },
    { text: 'need to create a mobile banking app', intent: 'scope.define' },
    
    // Additional Budget Examples (15 more)
    { text: 'budget is around 50000 dollars', intent: 'budget.set' },
    { text: 'we can allocate 15000 for this project', intent: 'budget.set' },
    { text: 'spending budget of 75000', intent: 'budget.set' },
    { text: 'have 30000 available for this', intent: 'budget.set' },
    { text: 'budget range is 20000 to 40000', intent: 'budget.set' },
    { text: 'can spend maximum 60000', intent: 'budget.set' },
    { text: 'budget limit is 25000', intent: 'budget.set' },
    { text: 'available funds are 45000', intent: 'budget.set' },
    { text: 'project budget is 80000', intent: 'budget.set' },
    { text: 'financial allocation of 35000', intent: 'budget.set' },
    { text: 'cost budget is 55000', intent: 'budget.set' },
    { text: 'expense limit of 40000', intent: 'budget.set' },
    { text: 'investment budget of 65000', intent: 'budget.set' },
    { text: 'funding available is 70000', intent: 'budget.set' },
    { text: 'budget ceiling is 90000', intent: 'budget.set' },
    
    // Additional Timeline Examples (15 more)
    { text: 'need completion by end of year', intent: 'timeline.set' },
    { text: 'deadline is in 4 months', intent: 'timeline.set' },
    { text: 'want it finished by summer', intent: 'timeline.set' },
    { text: 'due date is next quarter', intent: 'timeline.set' },
    { text: 'need delivery in 8 weeks', intent: 'timeline.set' },
    { text: 'timeline is 5 months', intent: 'timeline.set' },
    { text: 'completion target is spring', intent: 'timeline.set' },
    { text: 'deadline is mid-year', intent: 'timeline.set' },
    { text: 'need it ready by fall', intent: 'timeline.set' },
    { text: 'timeline of 10 weeks', intent: 'timeline.set' },
    { text: 'completion by year end', intent: 'timeline.set' },
    { text: 'deadline in 6 months', intent: 'timeline.set' },
    { text: 'need it done by winter', intent: 'timeline.set' },
    { text: 'timeline is 7 months', intent: 'timeline.set' },
    { text: 'completion target is q3', intent: 'timeline.set' },
    
    // Additional Deliverables Examples (15 more)
    { text: 'main deliverables are app and documentation', intent: 'deliverables.define' },
    { text: 'need to create user interface and backend', intent: 'deliverables.define' },
    { text: 'deliverables include website and mobile app', intent: 'deliverables.define' },
    { text: 'final outputs are prototype and testing report', intent: 'deliverables.define' },
    { text: 'need to produce marketing materials and website', intent: 'deliverables.define' },
    { text: 'deliverables are software and user manual', intent: 'deliverables.define' },
    { text: 'main outputs include database and api', intent: 'deliverables.define' },
    { text: 'need to create dashboard and reports', intent: 'deliverables.define' },
    { text: 'deliverables are mobile app and web portal', intent: 'deliverables.define' },
    { text: 'final products are website and mobile version', intent: 'deliverables.define' },
    { text: 'need to deliver software package and documentation', intent: 'deliverables.define' },
    { text: 'main deliverables are platform and integrations', intent: 'deliverables.define' },
    { text: 'outputs include application and admin panel', intent: 'deliverables.define' },
    { text: 'deliverables are system and training materials', intent: 'deliverables.define' },
    { text: 'need to create product and marketing website', intent: 'deliverables.define' },
    
    // Additional Dependencies Examples (15 more)
    { text: 'depends on user feedback and approval', intent: 'dependencies.define' },
    { text: 'need stakeholder sign-off first', intent: 'dependencies.define' },
    { text: 'waiting for technical requirements', intent: 'dependencies.define' },
    { text: 'blocked by infrastructure setup', intent: 'dependencies.define' },
    { text: 'requires third party integration', intent: 'dependencies.define' },
    { text: 'need external team coordination', intent: 'dependencies.define' },
    { text: 'depends on vendor delivery', intent: 'dependencies.define' },
    { text: 'waiting for security clearance', intent: 'dependencies.define' },
    { text: 'requires compliance approval', intent: 'dependencies.define' },
    { text: 'blocked by resource allocation', intent: 'dependencies.define' },
    { text: 'need technical architecture review', intent: 'dependencies.define' },
    { text: 'depends on data migration completion', intent: 'dependencies.define' },
    { text: 'waiting for design system approval', intent: 'dependencies.define' },
    { text: 'requires performance testing', intent: 'dependencies.define' },
    { text: 'blocked by user acceptance testing', intent: 'dependencies.define' },
    
    // Additional Response Examples (20 more)
    { text: 'that\'s exactly what i wanted', intent: 'response.positive' },
    { text: 'perfect that works for me', intent: 'response.positive' },
    { text: 'yes that\'s correct', intent: 'response.positive' },
    { text: 'great that looks perfect', intent: 'response.positive' },
    { text: 'excellent that\'s what i need', intent: 'response.positive' },
    { text: 'wonderful that\'s perfect', intent: 'response.positive' },
    { text: 'fantastic that works', intent: 'response.positive' },
    { text: 'brilliant that\'s exactly right', intent: 'response.positive' },
    { text: 'superb that\'s what i was looking for', intent: 'response.positive' },
    { text: 'outstanding that\'s perfect', intent: 'response.positive' },
    { text: 'amazing that works for me', intent: 'response.positive' },
    { text: 'terrific that\'s exactly what i need', intent: 'response.positive' },
    { text: 'marvelous that\'s perfect', intent: 'response.positive' },
    { text: 'splendid that works', intent: 'response.positive' },
    { text: 'magnificent that\'s exactly right', intent: 'response.positive' },
    { text: 'no that\'s not what i want', intent: 'response.negative' },
    { text: 'that\'s completely wrong', intent: 'response.negative' },
    { text: 'no way that\'s not it', intent: 'response.negative' },
    { text: 'that\'s totally incorrect', intent: 'response.negative' },
    { text: 'absolutely not that\'s wrong', intent: 'response.negative' },
    
    // General Help
    { text: 'help me', intent: 'general.help' },
    { text: 'help', intent: 'general.help' },
    { text: 'what can you do', intent: 'general.help' },
    { text: 'how do i', intent: 'general.help' },
    { text: 'guide me', intent: 'general.help' },
    { text: 'show me how', intent: 'general.help' },
    { text: 'instructions', intent: 'general.help' },
    { text: 'tutorial', intent: 'general.help' },
    { text: 'how to', intent: 'general.help' },
    { text: 'what should i do', intent: 'general.help' },
    
    // Thanks
    { text: 'thanks', intent: 'general.thanks' },
    { text: 'thank you', intent: 'general.thanks' },
    { text: 'appreciate it', intent: 'general.thanks' },
    { text: 'much appreciated', intent: 'general.thanks' },
    { text: 'grateful', intent: 'general.thanks' },
    { text: 'awesome thanks', intent: 'general.thanks' },
    { text: 'great help', intent: 'general.thanks' },
    { text: 'perfect thanks', intent: 'general.thanks' },
    
    // Project Name Changes
    { text: 'change the project name to downtown pet store', intent: 'project.rename' },
    { text: 'rename the project to coffee shop launch', intent: 'project.rename' },
    { text: 'call this project website redesign', intent: 'project.rename' },
    { text: 'name this project mobile app development', intent: 'project.rename' },
    { text: 'change project name to marketing campaign', intent: 'project.rename' },
    { text: 'rename project to food truck business', intent: 'project.rename' },
    { text: 'update project name to online store', intent: 'project.rename' },
    { text: 'set project name to restaurant opening', intent: 'project.rename' },
    { text: 'project name should be fitness center', intent: 'project.rename' },
    { text: 'call it tech startup', intent: 'project.rename' },
    { text: 'name it consulting business', intent: 'project.rename' },
    { text: 'let\'s call this bakery launch', intent: 'project.rename' },
    { text: 'let\'s name this event planning', intent: 'project.rename' },
    { text: 'change name to digital transformation', intent: 'project.rename' },
    { text: 'rename to product launch', intent: 'project.rename' },
    { text: 'update name to service expansion', intent: 'project.rename' },
    
    // Project Name Generation Intents - 100 examples for better NLP accuracy
    { text: 'i need a project plan for a new pet store that we are going to open in town', intent: 'project.name_generate' },
    { text: 'we have a budget of 30000 dollars for our pet store project', intent: 'project.name_generate' },
    { text: 'i want to start a coffee shop business in downtown', intent: 'project.name_generate' },
    { text: 'we are planning to launch a new restaurant in the mall', intent: 'project.name_generate' },
    { text: 'help me plan a mobile app for fitness tracking', intent: 'project.name_generate' },
    { text: 'i need to create a website for my consulting business', intent: 'project.name_generate' },
    { text: 'we are opening a bakery in the neighborhood', intent: 'project.name_generate' },
    { text: 'planning to start a tech startup for AI solutions', intent: 'project.name_generate' },
    { text: 'i want to launch an e-commerce platform for handmade crafts', intent: 'project.name_generate' },
    { text: 'we are developing a new software product for project management', intent: 'project.name_generate' },
    { text: 'help me plan a marketing campaign for our new product', intent: 'project.name_generate' },
    { text: 'i need to organize a corporate event for 500 people', intent: 'project.name_generate' },
    { text: 'we are renovating our office space to modernize it', intent: 'project.name_generate' },
    { text: 'planning a product launch for our new smartphone', intent: 'project.name_generate' },
    { text: 'i want to start a food truck business serving tacos', intent: 'project.name_generate' },
    { text: 'we are building a new warehouse for our logistics company', intent: 'project.name_generate' },
    { text: 'help me plan a digital transformation for our company', intent: 'project.name_generate' },
    { text: 'i need to create a mobile game for children', intent: 'project.name_generate' },
    { text: 'we are launching a new clothing brand online', intent: 'project.name_generate' },
    { text: 'planning to open a fitness center in the suburbs', intent: 'project.name_generate' },
    { text: 'i want to develop a healthcare app for patients', intent: 'project.name_generate' },
    { text: 'we are starting a tutoring service for students', intent: 'project.name_generate' },
    { text: 'help me plan a real estate development project', intent: 'project.name_generate' },
    { text: 'i need to create a social media platform for artists', intent: 'project.name_generate' },
    { text: 'we are launching a subscription box service for books', intent: 'project.name_generate' },
    { text: 'planning to start a cleaning service business', intent: 'project.name_generate' },
    { text: 'i want to develop a financial planning app', intent: 'project.name_generate' },
    { text: 'we are opening a yoga studio in the city center', intent: 'project.name_generate' },
    { text: 'help me plan a home renovation project', intent: 'project.name_generate' },
    { text: 'i need to create a learning management system', intent: 'project.name_generate' },
    { text: 'we are starting a delivery service for groceries', intent: 'project.name_generate' },
    { text: 'planning to launch a podcast about technology', intent: 'project.name_generate' },
    { text: 'i want to develop a travel booking platform', intent: 'project.name_generate' },
    { text: 'we are opening a craft brewery in the industrial district', intent: 'project.name_generate' },
    { text: 'help me plan a wedding planning business', intent: 'project.name_generate' },
    { text: 'i need to create a job board for remote workers', intent: 'project.name_generate' },
    { text: 'we are launching a beauty salon in the mall', intent: 'project.name_generate' },
    { text: 'planning to start a pet grooming service', intent: 'project.name_generate' },
    { text: 'i want to develop a meditation app for wellness', intent: 'project.name_generate' },
    { text: 'we are opening a hardware store in the neighborhood', intent: 'project.name_generate' },
    { text: 'help me plan a car dealership expansion', intent: 'project.name_generate' },
    { text: 'i need to create a music streaming platform', intent: 'project.name_generate' },
    { text: 'we are starting a landscaping business', intent: 'project.name_generate' },
    { text: 'planning to launch a fashion e-commerce site', intent: 'project.name_generate' },
    { text: 'i want to develop a language learning app', intent: 'project.name_generate' },
    { text: 'we are opening a pharmacy in the medical district', intent: 'project.name_generate' },
    { text: 'help me plan a construction project for a new building', intent: 'project.name_generate' },
    { text: 'i need to create a video conferencing platform', intent: 'project.name_generate' },
    { text: 'we are launching a meal prep service', intent: 'project.name_generate' },
    { text: 'planning to start a graphic design agency', intent: 'project.name_generate' },
    { text: 'i want to develop a cryptocurrency trading app', intent: 'project.name_generate' },
    { text: 'we are opening a bookstore in the downtown area', intent: 'project.name_generate' },
    { text: 'help me plan a solar panel installation business', intent: 'project.name_generate' },
    { text: 'i need to create a dating app for professionals', intent: 'project.name_generate' },
    { text: 'we are starting a home security company', intent: 'project.name_generate' },
    { text: 'planning to launch a virtual reality gaming center', intent: 'project.name_generate' },
    { text: 'i want to develop a recipe sharing platform', intent: 'project.name_generate' },
    { text: 'we are opening a veterinary clinic in the suburbs', intent: 'project.name_generate' },
    { text: 'help me plan a logistics optimization project', intent: 'project.name_generate' },
    { text: 'i need to create a crowdfunding platform', intent: 'project.name_generate' },
    { text: 'we are launching a personal training service', intent: 'project.name_generate' },
    { text: 'planning to start a photography studio', intent: 'project.name_generate' },
    { text: 'i want to develop a weather forecasting app', intent: 'project.name_generate' },
    { text: 'we are opening a furniture store in the shopping center', intent: 'project.name_generate' },
    { text: 'help me plan a waste management system', intent: 'project.name_generate' },
    { text: 'i need to create a news aggregation platform', intent: 'project.name_generate' },
    { text: 'we are starting a car rental service', intent: 'project.name_generate' },
    { text: 'planning to launch a 3D printing service', intent: 'project.name_generate' },
    { text: 'i want to develop a stock trading platform', intent: 'project.name_generate' },
    { text: 'we are opening a dental clinic in the medical plaza', intent: 'project.name_generate' },
    { text: 'help me plan a renewable energy project', intent: 'project.name_generate' },
    { text: 'i need to create a social networking app', intent: 'project.name_generate' },
    { text: 'we are launching a catering service for events', intent: 'project.name_generate' },
    { text: 'planning to start a legal consulting firm', intent: 'project.name_generate' },
    { text: 'i want to develop a habit tracking app', intent: 'project.name_generate' },
    { text: 'we are opening a toy store in the family mall', intent: 'project.name_generate' },
    { text: 'help me plan a water treatment facility', intent: 'project.name_generate' },
    { text: 'i need to create a file sharing platform', intent: 'project.name_generate' },
    { text: 'we are starting a bike rental service', intent: 'project.name_generate' },
    { text: 'planning to launch a drone delivery service', intent: 'project.name_generate' },
    { text: 'i want to develop a password manager app', intent: 'project.name_generate' },
    { text: 'we are opening a jewelry store in the luxury mall', intent: 'project.name_generate' },
    { text: 'help me plan a smart city infrastructure project', intent: 'project.name_generate' },
    { text: 'i need to create a video editing platform', intent: 'project.name_generate' },
    { text: 'we are launching a pet sitting service', intent: 'project.name_generate' },
    { text: 'planning to start a translation agency', intent: 'project.name_generate' },
    { text: 'i want to develop a sleep tracking app', intent: 'project.name_generate' },
    { text: 'we are opening a flower shop in the downtown area', intent: 'project.name_generate' },
    { text: 'help me plan a telecommunications network upgrade', intent: 'project.name_generate' },
    { text: 'i need to create a project management platform', intent: 'project.name_generate' },
    { text: 'we are starting a house cleaning service', intent: 'project.name_generate' },
    { text: 'planning to launch a virtual assistant service', intent: 'project.name_generate' },
    { text: 'i want to develop a calorie counting app', intent: 'project.name_generate' },
    { text: 'we are opening a sports equipment store', intent: 'project.name_generate' },
    { text: 'help me plan a highway construction project', intent: 'project.name_generate' },
    { text: 'i need to create a code collaboration platform', intent: 'project.name_generate' },
    { text: 'we are launching a dog walking service', intent: 'project.name_generate' },
    { text: 'planning to start a public relations agency', intent: 'project.name_generate' },
    { text: 'i want to develop a mood tracking app', intent: 'project.name_generate' },
    { text: 'we are opening a electronics store in the tech district', intent: 'project.name_generate' },
    { text: 'help me plan a bridge construction project', intent: 'project.name_generate' },
    { text: 'i need to create a cloud storage platform', intent: 'project.name_generate' },
    { text: 'we are starting a lawn care service', intent: 'project.name_generate' },
    { text: 'planning to launch a voice assistant service', intent: 'project.name_generate' },
    { text: 'i want to develop a expense tracking app', intent: 'project.name_generate' },
    { text: 'we are opening a music store in the arts district', intent: 'project.name_generate' },
    { text: 'help me plan a airport expansion project', intent: 'project.name_generate' },
    { text: 'i need to create a bug tracking platform', intent: 'project.name_generate' },
    { text: 'we are launching a senior care service', intent: 'project.name_generate' },
    { text: 'planning to start a market research firm', intent: 'project.name_generate' },
    { text: 'i want to develop a time tracking app', intent: 'project.name_generate' },
    { text: 'we are opening a art supply store', intent: 'project.name_generate' },
    { text: 'help me plan a dam construction project', intent: 'project.name_generate' },
    { text: 'i need to create a database management platform', intent: 'project.name_generate' },
    { text: 'we are starting a pest control service', intent: 'project.name_generate' },
    { text: 'planning to launch a chatbot service', intent: 'project.name_generate' },
    { text: 'i want to develop a goal setting app', intent: 'project.name_generate' },
    { text: 'we are opening a garden center in the suburbs', intent: 'project.name_generate' },
    { text: 'help me plan a power plant construction project', intent: 'project.name_generate' },
    { text: 'i need to create a version control platform', intent: 'project.name_generate' },
    { text: 'we are launching a child care service', intent: 'project.name_generate' },
    { text: 'planning to start a business consulting firm', intent: 'project.name_generate' },
    { text: 'i want to develop a productivity app', intent: 'project.name_generate' },
    { text: 'we are opening a auto parts store', intent: 'project.name_generate' },
    { text: 'help me plan a railway construction project', intent: 'project.name_generate' },
    { text: 'i need to create a testing platform', intent: 'project.name_generate' },
    { text: 'we are starting a security guard service', intent: 'project.name_generate' },
    { text: 'planning to launch a AI consulting service', intent: 'project.name_generate' },
    { text: 'i want to develop a note taking app', intent: 'project.name_generate' },
    { text: 'we are opening a thrift store in the community center', intent: 'project.name_generate' },
    { text: 'help me plan a tunnel construction project', intent: 'project.name_generate' },
    { text: 'i need to create a deployment platform', intent: 'project.name_generate' },
    { text: 'we are launching a elder care service', intent: 'project.name_generate' },
    { text: 'planning to start a financial consulting firm', intent: 'project.name_generate' },
    { text: 'i want to develop a reminder app', intent: 'project.name_generate' },
    { text: 'we are opening a pawn shop in the downtown area', intent: 'project.name_generate' },
    { text: 'help me plan a port construction project', intent: 'project.name_generate' },
    { text: 'i need to create a monitoring platform', intent: 'project.name_generate' },
    { text: 'we are starting a janitorial service', intent: 'project.name_generate' },
    { text: 'planning to launch a blockchain consulting service', intent: 'project.name_generate' },
    { text: 'i want to develop a calendar app', intent: 'project.name_generate' },
    { text: 'we are opening a antique store in the historic district', intent: 'project.name_generate' },
    { text: 'help me plan a stadium construction project', intent: 'project.name_generate' },
    { text: 'i need to create a analytics platform', intent: 'project.name_generate' },
    { text: 'we are launching a home maintenance service', intent: 'project.name_generate' },
    { text: 'planning to start a HR consulting firm', intent: 'project.name_generate' },
    { text: 'i want to develop a contact management app', intent: 'project.name_generate' },
    { text: 'we are opening a comic book store in the entertainment district', intent: 'project.name_generate' },
    { text: 'help me plan a hospital construction project', intent: 'project.name_generate' },
    { text: 'i need to create a backup platform', intent: 'project.name_generate' },
    { text: 'we are starting a snow removal service', intent: 'project.name_generate' },
    { text: 'planning to launch a cybersecurity consulting service', intent: 'project.name_generate' },
    { text: 'i want to develop a task management app', intent: 'project.name_generate' },
    { text: 'we are opening a hobby shop in the craft district', intent: 'project.name_generate' },
    { text: 'help me plan a school construction project', intent: 'project.name_generate' },
    { text: 'i need to create a logging platform', intent: 'project.name_generate' },
    { text: 'we are launching a pool cleaning service', intent: 'project.name_generate' },
    { text: 'planning to start a marketing consulting firm', intent: 'project.name_generate' },
    { text: 'i want to develop a password generator app', intent: 'project.name_generate' },
    { text: 'we are opening a gift shop in the tourist area', intent: 'project.name_generate' },
    { text: 'help me plan a library construction project', intent: 'project.name_generate' },
    { text: 'i need to create a security platform', intent: 'project.name_generate' },
    { text: 'we are starting a window cleaning service', intent: 'project.name_generate' },
    { text: 'planning to launch a sales consulting service', intent: 'project.name_generate' },
    { text: 'i want to develop a unit converter app', intent: 'project.name_generate' },
    { text: 'we are opening a souvenir shop in the cultural district', intent: 'project.name_generate' },
    { text: 'help me plan a museum construction project', intent: 'project.name_generate' },
    { text: 'i need to create a encryption platform', intent: 'project.name_generate' },
    { text: 'we are launching a carpet cleaning service', intent: 'project.name_generate' },
    { text: 'planning to start a operations consulting firm', intent: 'project.name_generate' },
    { text: 'i want to develop a calculator app', intent: 'project.name_generate' },
    { text: 'we are opening a novelty shop in the entertainment center', intent: 'project.name_generate' },
    { text: 'help me plan a theater construction project', intent: 'project.name_generate' },
    { text: 'i need to create a compression platform', intent: 'project.name_generate' },
    { text: 'we are starting a upholstery cleaning service', intent: 'project.name_generate' },
    { text: 'planning to launch a strategy consulting service', intent: 'project.name_generate' },
    { text: 'i want to develop a flashlight app', intent: 'project.name_generate' },
    { text: 'we are opening a party supply store in the celebration district', intent: 'project.name_generate' },
    { text: 'help me plan a convention center construction project', intent: 'project.name_generate' },
    { text: 'i need to create a compression platform', intent: 'project.name_generate' },
    { text: 'we are launching a air duct cleaning service', intent: 'project.name_generate' },
    { text: 'planning to start a innovation consulting firm', intent: 'project.name_generate' },
    { text: 'i want to develop a compass app', intent: 'project.name_generate' },
    { text: 'we are opening a costume shop in the theater district', intent: 'project.name_generate' },
    { text: 'help me plan a shopping mall construction project', intent: 'project.name_generate' },
    { text: 'i need to create a image processing platform', intent: 'project.name_generate' },
    { text: 'we are starting a chimney cleaning service', intent: 'project.name_generate' },
    { text: 'planning to launch a digital consulting service', intent: 'project.name_generate' },
    { text: 'i want to develop a level app', intent: 'project.name_generate' },
    
    // Status Queries
    { text: 'what is the project status', intent: 'project.status' },
    { text: 'show project status', intent: 'project.status' },
    { text: 'get status', intent: 'project.status' },
    { text: 'project progress', intent: 'project.status' },
    { text: 'how is the project going', intent: 'project.status' },
    { text: 'project update', intent: 'project.status' },
    { text: 'current status', intent: 'project.status' },
    { text: 'progress report', intent: 'project.status' },
    { text: 'where are we', intent: 'project.status' },
    { text: 'status check', intent: 'project.status' },
    
    // Timeline Queries
    { text: 'show timeline', intent: 'timeline.query' },
    { text: 'project timeline', intent: 'timeline.query' },
    { text: 'when is it due', intent: 'timeline.query' },
    { text: 'what\'s the schedule', intent: 'timeline.query' },
    { text: 'timeline overview', intent: 'timeline.query' },
    { text: 'project schedule', intent: 'timeline.query' },
    { text: 'when will it be done', intent: 'timeline.query' },
    { text: 'delivery date', intent: 'timeline.query' },
    { text: 'project dates', intent: 'timeline.query' },
    { text: 'milestones', intent: 'timeline.query' },
    
    // Stakeholders
    { text: 'add team member', intent: 'stakeholder.add' },
    { text: 'add member', intent: 'stakeholder.add' },
    { text: 'invite user', intent: 'stakeholder.add' },
    { text: 'include john in project', intent: 'stakeholder.add' },
    { text: 'add stakeholder', intent: 'stakeholder.add' },
    { text: 'team member', intent: 'stakeholder.add' },
    { text: 'collaborator', intent: 'stakeholder.add' },
    { text: 'project member', intent: 'stakeholder.add' },
    
    // Action Planning Intents - Gap-based planning
    { text: 'objectives missing budget set tasks incomplete', intent: 'action.ask_objectives' },
    { text: 'critical gap objectives no goals defined', intent: 'action.ask_objectives' },
    { text: 'objectives empty scope undefined', intent: 'action.ask_objectives' },
    { text: 'no objectives defined project goals missing', intent: 'action.ask_objectives' },
    { text: 'objectives gap critical priority', intent: 'action.ask_objectives' },
    { text: 'objectives missing high priority gap', intent: 'action.ask_objectives' },
    { text: 'objectives undefined need clarification', intent: 'action.ask_objectives' },
    { text: 'objectives area empty template incomplete', intent: 'action.ask_objectives' },
    { text: 'objectives missing blocks planning', intent: 'action.ask_objectives' },
    { text: 'objectives critical gap immediate attention', intent: 'action.ask_objectives' },
    
    { text: 'budget missing objectives set tasks incomplete', intent: 'action.ask_budget' },
    { text: 'budget gap high priority no financial plan', intent: 'action.ask_budget' },
    { text: 'budget undefined cost planning needed', intent: 'action.ask_budget' },
    { text: 'budget missing medium priority gap', intent: 'action.ask_budget' },
    { text: 'budget area empty financial planning', intent: 'action.ask_budget' },
    { text: 'budget gap blocks execution planning', intent: 'action.ask_budget' },
    { text: 'budget missing cost estimation needed', intent: 'action.ask_budget' },
    { text: 'budget undefined spending plan required', intent: 'action.ask_budget' },
    { text: 'budget gap medium priority impact', intent: 'action.ask_budget' },
    { text: 'budget missing financial resources unclear', intent: 'action.ask_budget' },
    
    { text: 'tasks missing objectives set budget set', intent: 'action.ask_tasks' },
    { text: 'tasks gap high priority timeline unclear', intent: 'action.ask_tasks' },
    { text: 'tasks undefined deliverables missing', intent: 'action.ask_tasks' },
    { text: 'tasks missing deadline planning needed', intent: 'action.ask_tasks' },
    { text: 'tasks gap medium priority execution plan', intent: 'action.ask_tasks' },
    { text: 'tasks area empty work breakdown needed', intent: 'action.ask_tasks' },
    { text: 'tasks missing schedule planning required', intent: 'action.ask_tasks' },
    { text: 'tasks undefined timeline planning needed', intent: 'action.ask_tasks' },
    { text: 'tasks gap blocks execution delivery', intent: 'action.ask_tasks' },
    { text: 'tasks missing work plan undefined', intent: 'action.ask_tasks' },
    
    { text: 'people missing objectives set budget set tasks set', intent: 'action.ask_people' },
    { text: 'people gap low priority stakeholders unclear', intent: 'action.ask_people' },
    { text: 'people undefined team planning needed', intent: 'action.ask_people' },
    { text: 'people missing stakeholder identification', intent: 'action.ask_people' },
    { text: 'people gap team composition planning', intent: 'action.ask_people' },
    { text: 'people area empty role assignment needed', intent: 'action.ask_people' },
    { text: 'people missing resource allocation unclear', intent: 'action.ask_people' },
    { text: 'people undefined responsibility planning', intent: 'action.ask_people' },
    { text: 'people gap minor impact team structure', intent: 'action.ask_people' },
    { text: 'people missing collaboration planning needed', intent: 'action.ask_people' },
    
    // Conversation stage planning
    { text: 'initial conversation 2 messages low engagement', intent: 'action.ask_objectives' },
    { text: 'early stage 5 messages exploration phase', intent: 'action.ask_objectives' },
    { text: 'beginning conversation 3 messages basic info', intent: 'action.ask_objectives' },
    { text: 'startup phase 4 messages foundation needed', intent: 'action.ask_objectives' },
    { text: 'introductory stage 1 message new user', intent: 'action.ask_objectives' },
    { text: 'initial contact 2 messages scope definition', intent: 'action.ask_objectives' },
    { text: 'early planning 3 messages basic requirements', intent: 'action.ask_objectives' },
    { text: 'conversation start 4 messages project initiation', intent: 'action.ask_objectives' },
    { text: 'new project 1 message fresh start', intent: 'action.ask_objectives' },
    { text: 'project beginning 2 messages initial planning', intent: 'action.ask_objectives' },
    
    { text: 'planning stage 10 messages detailed planning', intent: 'action.ask_budget' },
    { text: 'development phase 12 messages execution planning', intent: 'action.ask_tasks' },
    { text: 'detailed conversation 15 messages comprehensive planning', intent: 'action.ask_people' },
    { text: 'advanced stage 18 messages final planning', intent: 'action.provide_recommendation' },
    { text: 'mature conversation 20 messages optimization', intent: 'action.provide_recommendation' },
    { text: 'established project 25 messages maintenance', intent: 'action.provide_recommendation' },
    { text: 'ongoing project 30 messages monitoring', intent: 'action.provide_recommendation' },
    { text: 'active project 35 messages continuous improvement', intent: 'action.provide_recommendation' },
    { text: 'stable project 40 messages refinement', intent: 'action.provide_recommendation' },
    { text: 'long running project 50 messages evolution', intent: 'action.provide_recommendation' },
    
    // User engagement adaptation
    { text: 'high engagement detailed responses 100 word average', intent: 'action.ask_detailed' },
    { text: 'high engagement comprehensive answers thorough planning', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed communication style', intent: 'action.ask_detailed' },
    { text: 'high engagement comprehensive responses', intent: 'action.ask_detailed' },
    { text: 'high engagement thorough communication', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed interaction pattern', intent: 'action.ask_detailed' },
    { text: 'high engagement comprehensive planning style', intent: 'action.ask_detailed' },
    { text: 'high engagement thorough response pattern', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed question style', intent: 'action.ask_detailed' },
    { text: 'high engagement comprehensive approach', intent: 'action.ask_detailed' },
    
    { text: 'low engagement brief responses 20 word average', intent: 'action.ask_direct' },
    { text: 'low engagement short answers minimal planning', intent: 'action.ask_direct' },
    { text: 'low engagement brief communication style', intent: 'action.ask_direct' },
    { text: 'low engagement concise responses', intent: 'action.ask_direct' },
    { text: 'low engagement minimal communication', intent: 'action.ask_direct' },
    { text: 'low engagement brief interaction pattern', intent: 'action.ask_direct' },
    { text: 'low engagement concise planning style', intent: 'action.ask_direct' },
    { text: 'low engagement minimal response pattern', intent: 'action.ask_direct' },
    { text: 'low engagement brief question style', intent: 'action.ask_direct' },
    { text: 'low engagement concise approach', intent: 'action.ask_direct' },
    
    { text: 'medium engagement mixed responses 50 word average', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate answers balanced planning', intent: 'action.ask_balanced' },
    { text: 'medium engagement mixed communication style', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate responses', intent: 'action.ask_balanced' },
    { text: 'medium engagement balanced communication', intent: 'action.ask_balanced' },
    { text: 'medium engagement mixed interaction pattern', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate planning style', intent: 'action.ask_balanced' },
    { text: 'medium engagement balanced response pattern', intent: 'action.ask_balanced' },
    { text: 'medium engagement mixed question style', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate approach', intent: 'action.ask_balanced' },
    
    // Project complexity planning
    { text: 'high complexity project multiple stakeholders complex requirements', intent: 'action.escalate_complexity' },
    { text: 'complex project intricate dependencies advanced planning', intent: 'action.escalate_complexity' },
    { text: 'high complexity multiple phases complex deliverables', intent: 'action.escalate_complexity' },
    { text: 'complex project advanced requirements sophisticated planning', intent: 'action.escalate_complexity' },
    { text: 'high complexity intricate project detailed planning needed', intent: 'action.escalate_complexity' },
    { text: 'complex project multiple teams advanced coordination', intent: 'action.escalate_complexity' },
    { text: 'high complexity sophisticated requirements detailed analysis', intent: 'action.escalate_complexity' },
    { text: 'complex project intricate workflow advanced management', intent: 'action.escalate_complexity' },
    { text: 'high complexity multiple components sophisticated planning', intent: 'action.escalate_complexity' },
    { text: 'complex project advanced coordination detailed planning', intent: 'action.escalate_complexity' },
    
    { text: 'low complexity simple project basic requirements', intent: 'action.simplify_approach' },
    { text: 'simple project minimal stakeholders basic planning', intent: 'action.simplify_approach' },
    { text: 'low complexity straightforward requirements simple planning', intent: 'action.simplify_approach' },
    { text: 'simple project basic deliverables minimal complexity', intent: 'action.simplify_approach' },
    { text: 'low complexity uncomplicated project basic approach', intent: 'action.simplify_approach' },
    { text: 'simple project minimal dependencies straightforward planning', intent: 'action.simplify_approach' },
    { text: 'low complexity basic requirements simple coordination', intent: 'action.simplify_approach' },
    { text: 'simple project straightforward workflow basic management', intent: 'action.simplify_approach' },
    { text: 'low complexity minimal components basic planning', intent: 'action.simplify_approach' },
    { text: 'simple project basic coordination straightforward approach', intent: 'action.simplify_approach' },
    
    // Urgency planning
    { text: 'high urgency immediate deadline critical timeline', intent: 'action.ask_direct' },
    { text: 'urgent project tight deadline immediate action', intent: 'action.ask_direct' },
    { text: 'high urgency critical timeline fast execution', intent: 'action.ask_direct' },
    { text: 'urgent project immediate requirements quick planning', intent: 'action.ask_direct' },
    { text: 'high urgency time sensitive critical delivery', intent: 'action.ask_direct' },
    { text: 'urgent project fast timeline immediate response', intent: 'action.ask_direct' },
    { text: 'high urgency critical deadline immediate planning', intent: 'action.ask_direct' },
    { text: 'urgent project time critical fast execution', intent: 'action.ask_direct' },
    { text: 'high urgency immediate action critical timeline', intent: 'action.ask_direct' },
    { text: 'urgent project critical urgency fast delivery', intent: 'action.ask_direct' },
    
    { text: 'low urgency flexible timeline relaxed planning', intent: 'action.ask_exploratory' },
    { text: 'relaxed project flexible deadline thoughtful planning', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable timeline exploratory approach', intent: 'action.ask_exploratory' },
    { text: 'flexible project relaxed requirements thoughtful approach', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable timeline exploratory planning', intent: 'action.ask_exploratory' },
    { text: 'relaxed project flexible schedule thoughtful execution', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable deadline exploratory approach', intent: 'action.ask_exploratory' },
    { text: 'flexible project relaxed timeline thoughtful planning', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable schedule exploratory delivery', intent: 'action.ask_exploratory' },
    { text: 'relaxed project flexible requirements thoughtful execution', intent: 'action.ask_exploratory' },
    
    // Recommendation scenarios
    { text: 'objectives complete budget set tasks defined people assigned', intent: 'action.provide_recommendation' },
    { text: 'all areas complete project well defined comprehensive planning', intent: 'action.provide_recommendation' },
    { text: 'objectives set budget defined tasks planned people identified', intent: 'action.provide_recommendation' },
    { text: 'project fully defined comprehensive information complete planning', intent: 'action.provide_recommendation' },
    { text: 'all gaps resolved project information complete', intent: 'action.provide_recommendation' },
    { text: 'objectives clear budget set tasks planned stakeholders identified', intent: 'action.provide_recommendation' },
    { text: 'project well defined all areas complete comprehensive planning', intent: 'action.provide_recommendation' },
    { text: 'objectives defined budget set tasks clear people assigned', intent: 'action.provide_recommendation' },
    { text: 'project information complete all areas defined', intent: 'action.provide_recommendation' },
    { text: 'objectives set budget planned tasks defined team assigned', intent: 'action.provide_recommendation' },
    
    // Clarification scenarios
    { text: 'unclear response ambiguous answer need clarification', intent: 'action.request_clarification' },
    { text: 'confusing response unclear meaning clarification needed', intent: 'action.request_clarification' },
    { text: 'ambiguous answer unclear intent need more info', intent: 'action.request_clarification' },
    { text: 'unclear response confusing message clarification required', intent: 'action.request_clarification' },
    { text: 'ambiguous answer unclear meaning need clarification', intent: 'action.request_clarification' },
    { text: 'confusing response unclear intent clarification needed', intent: 'action.request_clarification' },
    { text: 'unclear answer ambiguous message need more details', intent: 'action.request_clarification' },
    { text: 'confusing response unclear meaning clarification required', intent: 'action.request_clarification' },
    { text: 'ambiguous answer unclear intent need clarification', intent: 'action.request_clarification' },
    { text: 'unclear response confusing meaning clarification needed', intent: 'action.request_clarification' },
    
    // Continue planning scenarios
    { text: 'objectives partial budget missing tasks incomplete', intent: 'action.continue_planning' },
    { text: 'partial information some gaps remain planning continues', intent: 'action.continue_planning' },
    { text: 'objectives set budget partial tasks incomplete', intent: 'action.continue_planning' },
    { text: 'some areas complete others need attention continue planning', intent: 'action.continue_planning' },
    { text: 'objectives clear budget missing tasks partial', intent: 'action.continue_planning' },
    { text: 'partial completion some gaps resolved continue planning', intent: 'action.continue_planning' },
    { text: 'objectives defined budget unclear tasks incomplete', intent: 'action.continue_planning' },
    { text: 'mixed completion some areas done others need work', intent: 'action.continue_planning' },
    { text: 'objectives set budget partial tasks undefined', intent: 'action.continue_planning' },
    { text: 'partial information gaps remain continue planning', intent: 'action.continue_planning' },
    
    // Gap Detection Intents - Single critical gaps
    { text: 'objectives missing empty template area critical gap', intent: 'gap.critical_objectives' },
    { text: 'objectives area empty no goals defined critical priority', intent: 'gap.critical_objectives' },
    { text: 'objectives undefined scope missing critical gap', intent: 'gap.critical_objectives' },
    { text: 'no objectives defined project goals missing critical', intent: 'gap.critical_objectives' },
    { text: 'objectives gap critical blocks everything planning', intent: 'gap.critical_objectives' },
    { text: 'objectives missing critical priority immediate attention', intent: 'gap.critical_objectives' },
    { text: 'objectives empty template incomplete critical gap', intent: 'gap.critical_objectives' },
    { text: 'objectives undefined critical dependency blocks all', intent: 'gap.critical_objectives' },
    { text: 'objectives missing critical foundation needed', intent: 'gap.critical_objectives' },
    { text: 'objectives area empty critical gap blocks planning', intent: 'gap.critical_objectives' },
    
    { text: 'budget missing high priority gap financial planning', intent: 'gap.high_priority_budget' },
    { text: 'budget area empty high priority cost planning needed', intent: 'gap.high_priority_budget' },
    { text: 'budget undefined high priority financial resources unclear', intent: 'gap.high_priority_budget' },
    { text: 'budget gap high priority blocks execution planning', intent: 'gap.high_priority_budget' },
    { text: 'budget missing high priority cost estimation needed', intent: 'gap.high_priority_budget' },
    { text: 'budget area empty high priority spending plan required', intent: 'gap.high_priority_budget' },
    { text: 'budget gap high priority medium impact blocks execution', intent: 'gap.high_priority_budget' },
    { text: 'budget missing high priority financial planning needed', intent: 'gap.high_priority_budget' },
    { text: 'budget undefined high priority cost planning required', intent: 'gap.high_priority_budget' },
    { text: 'budget gap high priority financial resources unclear', intent: 'gap.high_priority_budget' },
    
    { text: 'tasks missing medium priority gap timeline unclear', intent: 'gap.medium_tasks' },
    { text: 'tasks area empty medium priority deliverables missing', intent: 'gap.medium_tasks' },
    { text: 'tasks undefined medium priority deadline planning needed', intent: 'gap.medium_tasks' },
    { text: 'tasks gap medium priority execution plan work breakdown', intent: 'gap.medium_tasks' },
    { text: 'tasks missing medium priority schedule planning required', intent: 'gap.medium_tasks' },
    { text: 'tasks area empty medium priority timeline planning needed', intent: 'gap.medium_tasks' },
    { text: 'tasks gap medium priority blocks execution delivery', intent: 'gap.medium_tasks' },
    { text: 'tasks missing medium priority work plan undefined', intent: 'gap.medium_tasks' },
    { text: 'tasks undefined medium priority execution planning needed', intent: 'gap.medium_tasks' },
    { text: 'tasks gap medium priority work breakdown needed', intent: 'gap.medium_tasks' },
    
    { text: 'people missing low priority gap stakeholders unclear', intent: 'gap.low_people' },
    { text: 'people area empty low priority team planning needed', intent: 'gap.low_people' },
    { text: 'people undefined low priority stakeholder identification', intent: 'gap.low_people' },
    { text: 'people gap low priority team composition planning', intent: 'gap.low_people' },
    { text: 'people missing low priority role assignment needed', intent: 'gap.low_people' },
    { text: 'people area empty low priority resource allocation unclear', intent: 'gap.low_people' },
    { text: 'people gap low priority minor impact team structure', intent: 'gap.low_people' },
    { text: 'people missing low priority collaboration planning needed', intent: 'gap.low_people' },
    { text: 'people undefined low priority responsibility planning', intent: 'gap.low_people' },
    { text: 'people gap low priority minor impact coordination', intent: 'gap.low_people' },
    
    // Multiple gap combinations
    { text: 'objectives missing budget missing tasks incomplete', intent: 'gap.prioritize_multiple' },
    { text: 'objectives empty budget undefined tasks missing people unclear', intent: 'gap.prioritize_multiple' },
    { text: 'multiple gaps objectives budget tasks people missing', intent: 'gap.prioritize_multiple' },
    { text: 'objectives missing budget gap tasks incomplete people undefined', intent: 'gap.prioritize_multiple' },
    { text: 'objectives empty budget missing tasks undefined people gap', intent: 'gap.prioritize_multiple' },
    { text: 'objectives gap budget missing tasks incomplete people missing', intent: 'gap.prioritize_multiple' },
    { text: 'objectives undefined budget empty tasks missing people unclear', intent: 'gap.prioritize_multiple' },
    { text: 'objectives missing budget gap tasks undefined people incomplete', intent: 'gap.prioritize_multiple' },
    { text: 'objectives empty budget missing tasks gap people undefined', intent: 'gap.prioritize_multiple' },
    { text: 'objectives gap budget empty tasks missing people incomplete', intent: 'gap.prioritize_multiple' },
    
    // Dependency-based gaps
    { text: 'tasks depend on objectives objectives missing critical dependency', intent: 'gap.analyze_dependencies' },
    { text: 'budget depends on objectives objectives missing dependency analysis', intent: 'gap.analyze_dependencies' },
    { text: 'people depend on tasks tasks missing dependency blocks team', intent: 'gap.analyze_dependencies' },
    { text: 'tasks depend on budget budget missing dependency affects timeline', intent: 'gap.analyze_dependencies' },
    { text: 'objectives foundation for all objectives missing dependency blocks', intent: 'gap.analyze_dependencies' },
    { text: 'tasks depend on objectives budget tasks missing dependency chain', intent: 'gap.analyze_dependencies' },
    { text: 'people depend on tasks objectives tasks missing dependency affects team', intent: 'gap.analyze_dependencies' },
    { text: 'budget depends on objectives tasks objectives missing dependency blocks', intent: 'gap.analyze_dependencies' },
    { text: 'tasks depend on objectives people objectives missing dependency chain', intent: 'gap.analyze_dependencies' },
    { text: 'multiple dependencies objectives missing blocks all other areas', intent: 'gap.analyze_dependencies' },
    
    // Completion-based analysis
    { text: 'objectives complete budget set tasks missing people incomplete', intent: 'gap.partial_completion' },
    { text: 'objectives set budget complete tasks missing people undefined', intent: 'gap.partial_completion' },
    { text: 'objectives complete budget missing tasks set people incomplete', intent: 'gap.partial_completion' },
    { text: 'objectives set budget missing tasks complete people undefined', intent: 'gap.partial_completion' },
    { text: 'objectives missing budget complete tasks set people incomplete', intent: 'gap.partial_completion' },
    { text: 'objectives incomplete budget set tasks missing people complete', intent: 'gap.partial_completion' },
    { text: 'objectives set budget incomplete tasks missing people complete', intent: 'gap.partial_completion' },
    { text: 'objectives missing budget incomplete tasks set people complete', intent: 'gap.partial_completion' },
    { text: 'objectives incomplete budget missing tasks complete people set', intent: 'gap.partial_completion' },
    { text: 'objectives complete budget incomplete tasks missing people set', intent: 'gap.partial_completion' },
    
    { text: 'objectives complete budget complete tasks complete people complete', intent: 'gap.all_complete' },
    { text: 'all areas complete project fully defined no gaps remain', intent: 'gap.all_complete' },
    { text: 'objectives set budget defined tasks planned people assigned', intent: 'gap.all_complete' },
    { text: 'project fully defined comprehensive information complete planning', intent: 'gap.all_complete' },
    { text: 'all gaps resolved project information complete comprehensive', intent: 'gap.all_complete' },
    { text: 'objectives clear budget set tasks planned stakeholders identified', intent: 'gap.all_complete' },
    { text: 'project well defined all areas complete comprehensive planning', intent: 'gap.all_complete' },
    { text: 'objectives defined budget set tasks clear people assigned', intent: 'gap.all_complete' },
    { text: 'project information complete all areas defined comprehensive', intent: 'gap.all_complete' },
    { text: 'objectives set budget planned tasks defined team assigned', intent: 'gap.all_complete' },
    
    // Priority scoring scenarios
    { text: 'objectives critical budget high tasks medium people low priority', intent: 'gap.priority_scoring' },
    { text: 'objectives critical priority budget high priority tasks medium people low', intent: 'gap.priority_scoring' },
    { text: 'objectives critical impact budget high impact tasks medium people low', intent: 'gap.priority_scoring' },
    { text: 'objectives blocks everything budget blocks planning tasks blocks execution', intent: 'gap.priority_scoring' },
    { text: 'objectives critical dependency budget high dependency tasks medium people low', intent: 'gap.priority_scoring' },
    { text: 'objectives immediate attention budget plan soon tasks schedule people monitor', intent: 'gap.priority_scoring' },
    { text: 'objectives critical gap budget high gap tasks medium gap people low gap', intent: 'gap.priority_scoring' },
    { text: 'objectives critical priority score budget high priority score tasks medium', intent: 'gap.priority_scoring' },
    { text: 'objectives critical impact score budget high impact score tasks medium', intent: 'gap.priority_scoring' },
    { text: 'objectives critical blocks all budget high blocks planning tasks medium', intent: 'gap.priority_scoring' },
    
    // Impact analysis scenarios
    { text: 'objectives missing blocks everything prevents all planning', intent: 'gap.impact_analysis' },
    { text: 'budget missing blocks execution planning affects timeline', intent: 'gap.impact_analysis' },
    { text: 'tasks missing blocks execution delivery affects completion', intent: 'gap.impact_analysis' },
    { text: 'people missing minor impact affects coordination only', intent: 'gap.impact_analysis' },
    { text: 'objectives missing blocks everything budget tasks people', intent: 'gap.impact_analysis' },
    { text: 'budget missing blocks planning execution timeline delivery', intent: 'gap.impact_analysis' },
    { text: 'tasks missing blocks execution delivery completion timeline', intent: 'gap.impact_analysis' },
    { text: 'people missing minor impact coordination team structure', intent: 'gap.impact_analysis' },
    { text: 'objectives missing critical impact blocks all other areas', intent: 'gap.impact_analysis' },
    { text: 'budget missing high impact blocks execution planning', intent: 'gap.impact_analysis' },
    
    // Template area analysis
    { text: 'template areas empty objectives empty budget empty tasks empty', intent: 'gap.template_analysis' },
    { text: 'template areas missing objectives missing budget missing tasks missing', intent: 'gap.template_analysis' },
    { text: 'template areas undefined objectives undefined budget undefined tasks undefined', intent: 'gap.template_analysis' },
    { text: 'template areas incomplete objectives incomplete budget incomplete tasks incomplete', intent: 'gap.template_analysis' },
    { text: 'template areas partial objectives partial budget partial tasks partial', intent: 'gap.template_analysis' },
    { text: 'template areas empty missing undefined incomplete partial', intent: 'gap.template_analysis' },
    { text: 'template areas need completion objectives need completion budget need', intent: 'gap.template_analysis' },
    { text: 'template areas require definition objectives require budget require tasks require', intent: 'gap.template_analysis' },
    { text: 'template areas need planning objectives need budget need tasks need', intent: 'gap.template_analysis' },
    { text: 'template areas need clarification objectives need budget need tasks need', intent: 'gap.template_analysis' },
    
    // Gap reasoning scenarios
    { text: 'objectives missing reasoning blocks all planning prevents progress', intent: 'gap.reasoning_analysis' },
    { text: 'budget missing reasoning blocks execution planning affects resources', intent: 'gap.reasoning_analysis' },
    { text: 'tasks missing reasoning blocks execution delivery affects timeline', intent: 'gap.reasoning_analysis' },
    { text: 'people missing reasoning affects coordination team structure minor', intent: 'gap.reasoning_analysis' },
    { text: 'objectives missing reasoning critical foundation blocks everything', intent: 'gap.reasoning_analysis' },
    { text: 'budget missing reasoning high priority affects execution planning', intent: 'gap.reasoning_analysis' },
    { text: 'tasks missing reasoning medium priority affects delivery execution', intent: 'gap.reasoning_analysis' },
    { text: 'people missing reasoning low priority affects coordination only', intent: 'gap.reasoning_analysis' },
    { text: 'objectives missing reasoning without scope cannot plan timeline budget', intent: 'gap.reasoning_analysis' },
    { text: 'budget missing reasoning without budget cannot plan execution timeline', intent: 'gap.reasoning_analysis' },
    
    // Gap resolution scenarios
    { text: 'objectives gap resolved budget gap remains tasks gap remains', intent: 'gap.resolution_analysis' },
    { text: 'objectives complete budget gap resolved tasks gap remains people gap', intent: 'gap.resolution_analysis' },
    { text: 'objectives resolved budget resolved tasks gap remains people gap remains', intent: 'gap.resolution_analysis' },
    { text: 'objectives complete budget complete tasks gap resolved people gap remains', intent: 'gap.resolution_analysis' },
    { text: 'objectives resolved budget gap resolved tasks resolved people gap remains', intent: 'gap.resolution_analysis' },
    { text: 'objectives complete budget gap resolved tasks gap resolved people gap resolved', intent: 'gap.resolution_analysis' },
    { text: 'objectives resolved budget resolved tasks resolved people resolved all complete', intent: 'gap.resolution_analysis' },
    { text: 'objectives gap resolved budget gap resolved tasks gap resolved people gap resolved', intent: 'gap.resolution_analysis' },
    { text: 'objectives complete budget complete tasks complete people complete all resolved', intent: 'gap.resolution_analysis' },
    { text: 'objectives resolved budget resolved tasks resolved people resolved project complete', intent: 'gap.resolution_analysis' },
    
    // Gap evolution scenarios
    { text: 'objectives gap evolved budget gap new tasks gap changed people gap updated', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap changed budget gap evolved tasks gap new people gap updated', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap updated budget gap changed tasks gap evolved people gap new', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap new budget gap updated tasks gap changed people gap evolved', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap changed budget gap new tasks gap updated people gap evolved', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap evolved budget gap changed tasks gap new people gap updated', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap updated budget gap evolved tasks gap changed people gap new', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap new budget gap changed tasks gap evolved people gap updated', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap changed budget gap updated tasks gap new people gap evolved', intent: 'gap.evolution_analysis' },
    { text: 'objectives gap evolved budget gap new tasks gap updated people gap changed', intent: 'gap.evolution_analysis' },
    
    // Additional Action Planning Examples (100 more)
    
    // Complex gap scenarios (20 examples)
    { text: 'objectives missing budget undefined tasks incomplete people unclear multiple gaps', intent: 'action.ask_objectives' },
    { text: 'objectives empty budget gap tasks missing people undefined complex situation', intent: 'action.ask_objectives' },
    { text: 'objectives undefined budget missing tasks incomplete people unclear multiple areas', intent: 'action.ask_objectives' },
    { text: 'objectives missing budget gap tasks undefined people missing complex gaps', intent: 'action.ask_objectives' },
    { text: 'objectives empty budget missing tasks gap people undefined multiple issues', intent: 'action.ask_objectives' },
    { text: 'objectives gap budget undefined tasks missing people incomplete complex scenario', intent: 'action.ask_objectives' },
    { text: 'objectives missing budget empty tasks undefined people gap multiple problems', intent: 'action.ask_objectives' },
    { text: 'objectives undefined budget missing tasks incomplete people unclear complex gaps', intent: 'action.ask_objectives' },
    { text: 'objectives missing budget gap tasks missing people undefined multiple areas', intent: 'action.ask_objectives' },
    { text: 'objectives empty budget missing tasks undefined people gap complex situation', intent: 'action.ask_objectives' },
    { text: 'objectives gap budget missing tasks incomplete people undefined multiple gaps', intent: 'action.ask_objectives' },
    { text: 'objectives missing budget undefined tasks gap people missing complex scenario', intent: 'action.ask_objectives' },
    { text: 'objectives undefined budget missing tasks missing people unclear multiple issues', intent: 'action.ask_objectives' },
    { text: 'objectives missing budget gap tasks undefined people incomplete complex gaps', intent: 'action.ask_objectives' },
    { text: 'objectives empty budget missing tasks gap people undefined multiple problems', intent: 'action.ask_objectives' },
    { text: 'objectives gap budget undefined tasks missing people unclear complex situation', intent: 'action.ask_objectives' },
    { text: 'objectives missing budget missing tasks incomplete people undefined multiple areas', intent: 'action.ask_objectives' },
    { text: 'objectives undefined budget gap tasks missing people gap complex gaps', intent: 'action.ask_objectives' },
    { text: 'objectives missing budget missing tasks gap people unclear multiple issues', intent: 'action.ask_objectives' },
    { text: 'objectives empty budget undefined tasks missing people missing complex scenario', intent: 'action.ask_objectives' },
    
    // High engagement detailed scenarios (15 examples)
    { text: 'high engagement detailed responses comprehensive planning thorough analysis', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed communication comprehensive approach thorough planning', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed interaction comprehensive analysis thorough approach', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed responses comprehensive strategy thorough planning', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed communication comprehensive analysis thorough approach', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed interaction comprehensive planning thorough strategy', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed responses comprehensive approach thorough analysis', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed communication comprehensive strategy thorough planning', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed interaction comprehensive analysis thorough strategy', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed responses comprehensive planning thorough approach', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed communication comprehensive approach thorough strategy', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed interaction comprehensive strategy thorough analysis', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed responses comprehensive analysis thorough planning', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed communication comprehensive planning thorough analysis', intent: 'action.ask_detailed' },
    { text: 'high engagement detailed interaction comprehensive approach thorough planning', intent: 'action.ask_detailed' },
    
    // Low engagement direct scenarios (15 examples)
    { text: 'low engagement brief responses minimal planning concise approach', intent: 'action.ask_direct' },
    { text: 'low engagement brief communication minimal approach concise planning', intent: 'action.ask_direct' },
    { text: 'low engagement brief interaction minimal strategy concise approach', intent: 'action.ask_direct' },
    { text: 'low engagement brief responses minimal analysis concise planning', intent: 'action.ask_direct' },
    { text: 'low engagement brief communication minimal planning concise strategy', intent: 'action.ask_direct' },
    { text: 'low engagement brief interaction minimal approach concise analysis', intent: 'action.ask_direct' },
    { text: 'low engagement brief responses minimal strategy concise approach', intent: 'action.ask_direct' },
    { text: 'low engagement brief communication minimal analysis concise planning', intent: 'action.ask_direct' },
    { text: 'low engagement brief interaction minimal planning concise strategy', intent: 'action.ask_direct' },
    { text: 'low engagement brief responses minimal approach concise analysis', intent: 'action.ask_direct' },
    { text: 'low engagement brief communication minimal strategy concise planning', intent: 'action.ask_direct' },
    { text: 'low engagement brief interaction minimal analysis concise approach', intent: 'action.ask_direct' },
    { text: 'low engagement brief responses minimal planning concise strategy', intent: 'action.ask_direct' },
    { text: 'low engagement brief communication minimal approach concise analysis', intent: 'action.ask_direct' },
    { text: 'low engagement brief interaction minimal strategy concise planning', intent: 'action.ask_direct' },
    
    // Medium engagement balanced scenarios (15 examples)
    { text: 'medium engagement moderate responses balanced planning moderate approach', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate communication balanced approach moderate planning', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate interaction balanced strategy moderate analysis', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate responses balanced analysis moderate planning', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate communication balanced planning moderate strategy', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate interaction balanced approach moderate analysis', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate responses balanced strategy moderate planning', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate communication balanced analysis moderate approach', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate interaction balanced planning moderate strategy', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate responses balanced approach moderate analysis', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate communication balanced strategy moderate planning', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate interaction balanced analysis moderate approach', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate responses balanced planning moderate strategy', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate communication balanced approach moderate analysis', intent: 'action.ask_balanced' },
    { text: 'medium engagement moderate interaction balanced strategy moderate planning', intent: 'action.ask_balanced' },
    
    // Urgency-based scenarios (15 examples)
    { text: 'high urgency immediate deadline critical timeline fast execution urgent', intent: 'action.ask_direct' },
    { text: 'urgent project tight deadline immediate action critical timeline fast', intent: 'action.ask_direct' },
    { text: 'high urgency critical timeline immediate response urgent project fast', intent: 'action.ask_direct' },
    { text: 'urgent project immediate requirements critical deadline fast execution', intent: 'action.ask_direct' },
    { text: 'high urgency time sensitive immediate action critical timeline urgent', intent: 'action.ask_direct' },
    { text: 'urgent project fast timeline critical deadline immediate response fast', intent: 'action.ask_direct' },
    { text: 'high urgency critical deadline immediate planning urgent project fast', intent: 'action.ask_direct' },
    { text: 'urgent project time critical immediate action fast execution critical', intent: 'action.ask_direct' },
    { text: 'high urgency immediate action critical timeline urgent project fast', intent: 'action.ask_direct' },
    { text: 'urgent project critical urgency immediate response fast delivery critical', intent: 'action.ask_direct' },
    { text: 'high urgency immediate deadline critical timeline fast execution urgent', intent: 'action.ask_direct' },
    { text: 'urgent project tight deadline immediate action critical timeline fast', intent: 'action.ask_direct' },
    { text: 'high urgency critical timeline immediate response urgent project fast', intent: 'action.ask_direct' },
    { text: 'urgent project immediate requirements critical deadline fast execution', intent: 'action.ask_direct' },
    { text: 'high urgency time sensitive immediate action critical timeline urgent', intent: 'action.ask_direct' },
    
    // Low urgency exploratory scenarios (10 examples)
    { text: 'low urgency comfortable timeline exploratory planning relaxed approach', intent: 'action.ask_exploratory' },
    { text: 'flexible project relaxed requirements thoughtful approach exploratory planning', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable deadline exploratory approach relaxed planning', intent: 'action.ask_exploratory' },
    { text: 'flexible project relaxed timeline thoughtful execution exploratory approach', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable schedule exploratory delivery relaxed planning', intent: 'action.ask_exploratory' },
    { text: 'relaxed project flexible requirements thoughtful execution exploratory planning', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable timeline exploratory approach relaxed execution', intent: 'action.ask_exploratory' },
    { text: 'flexible project relaxed deadline thoughtful planning exploratory execution', intent: 'action.ask_exploratory' },
    { text: 'low urgency comfortable requirements exploratory delivery relaxed approach', intent: 'action.ask_exploratory' },
    { text: 'relaxed project flexible timeline thoughtful approach exploratory planning', intent: 'action.ask_exploratory' },
    
    // Project complexity scenarios (10 examples)
    { text: 'complex project multiple stakeholders advanced requirements sophisticated planning', intent: 'action.escalate_complexity' },
    { text: 'sophisticated project advanced complexity multiple dependencies complex planning', intent: 'action.escalate_complexity' },
    { text: 'complex project advanced requirements multiple stakeholders sophisticated approach', intent: 'action.escalate_complexity' },
    { text: 'sophisticated project complex dependencies advanced planning multiple stakeholders', intent: 'action.escalate_complexity' },
    { text: 'complex project advanced complexity sophisticated requirements multiple dependencies', intent: 'action.escalate_complexity' },
    { text: 'sophisticated project complex planning advanced stakeholders multiple requirements', intent: 'action.escalate_complexity' },
    { text: 'complex project advanced dependencies sophisticated planning multiple stakeholders', intent: 'action.escalate_complexity' },
    { text: 'sophisticated project complex requirements advanced planning multiple dependencies', intent: 'action.escalate_complexity' },
    { text: 'complex project advanced stakeholders sophisticated dependencies multiple planning', intent: 'action.escalate_complexity' },
    { text: 'sophisticated project complex approach advanced requirements multiple stakeholders', intent: 'action.escalate_complexity' },
    
    // Simple project scenarios (10 examples)
    { text: 'simple project straightforward requirements basic planning streamlined approach', intent: 'action.simplify_approach' },
    { text: 'straightforward project basic requirements simple planning streamlined execution', intent: 'action.simplify_approach' },
    { text: 'simple project basic requirements straightforward planning streamlined approach', intent: 'action.simplify_approach' },
    { text: 'straightforward project simple requirements basic planning streamlined execution', intent: 'action.simplify_approach' },
    { text: 'simple project streamlined requirements basic planning straightforward approach', intent: 'action.simplify_approach' },
    { text: 'straightforward project streamlined requirements simple planning basic execution', intent: 'action.simplify_approach' },
    { text: 'simple project basic planning straightforward requirements streamlined execution', intent: 'action.simplify_approach' },
    { text: 'straightforward project simple approach basic requirements streamlined planning', intent: 'action.simplify_approach' },
    { text: 'simple project streamlined approach basic requirements straightforward execution', intent: 'action.simplify_approach' },
    { text: 'straightforward project basic approach simple requirements streamlined planning', intent: 'action.simplify_approach' },
];

// Response templates for each intent
export const responseTemplates = {
    'project.create': [
        'I\'ll help you create a new project.',
        'Let\'s set up a new project for you.',
        'Creating a new project now.'
    ],
    'scope.define': [
        'Perfect! I can see you\'re planning a new project. Let\'s build a comprehensive plan for your venture.',
        'Excellent! This sounds like an interesting project. I\'ll help you create a detailed project plan.',
        'Great choice! Let\'s develop a strategic plan for your project.',
        'Fantastic! I\'ll help you create a complete project plan.',
        'Wonderful! Let\'s build a comprehensive strategy for your new project.'
    ],
    'budget.set': [
        'Excellent! I\'ve noted your budget allocation. This will help us plan resources and scope appropriately.',
        'Perfect! Budget information is crucial for project planning. I\'ll factor this into our strategy.',
        'Great! Having a clear budget helps us make informed decisions about project scope and timeline.',
        'Outstanding! Budget clarity enables us to plan effectively and avoid scope creep.',
        'Wonderful! With your budget defined, we can now plan realistic deliverables and timeline.'
    ],
    'timeline.set': [
        'Perfect! I\'ve recorded your timeline requirements. This helps us plan milestones and deliverables.',
        'Excellent! Timeline clarity is essential for project success. I\'ll structure our plan accordingly.',
        'Great! With your deadline in mind, we can prioritize tasks and allocate resources effectively.',
        'Fantastic! A clear timeline helps us create realistic project milestones and checkpoints.',
        'Outstanding! Timeline definition enables us to plan backward from your delivery date.'
    ],
    'tasks.create': [
        'Let me add tasks to your project.',
        'I\'ll create those tasks for you.',
        'Adding tasks to your project.'
    ],
    'tasks.list': [
        'Here are your project tasks.',
        'Current tasks overview:',
        'Let me show you the tasks.'
    ],
    'tasks.complete': [
        'Great! I\'ll mark that task as complete.',
        'Task completed successfully.',
        'Excellent work! Task marked as done.'
    ],
    'deliverables.define': [
        'I\'ll add those deliverables to your project.',
        'Deliverables updated successfully.',
        'Setting your project deliverables.'
    ],
    'dependencies.define': [
        'I\'ll note those dependencies.',
        'Dependencies updated successfully.',
        'Recording project dependencies.'
    ],
    'response.positive': [
        'Great! Let\'s continue.',
        'Perfect! Moving forward.',
        'Excellent! Next steps:'
    ],
    'response.negative': [
        'I\'ll make those changes.',
        'Let me update that for you.',
        'Making the requested changes.'
    ],
    'general.clarify': [
        'I\'d be happy to explain more.',
        'Let me provide more details.',
        'I\'ll clarify that for you.'
    ],
    'general.help': [
        'I\'m here to help you with your project management.',
        'I can help you create projects, manage tasks, and more.',
        'What would you like to do with your project?'
    ],
    'general.thanks': [
        'You\'re welcome!',
        'Happy to help!',
        'My pleasure!'
    ],
    'project.rename': [
        'Perfect! I\'ve updated the project name.',
        'Great! The project has been renamed.',
        'Done! Your project name has been changed.',
        'Excellent! I\'ve set the new project name.',
        'Updated! The project is now renamed.'
    ],
    'project.name_generate': [
        'Perfect! I can see you\'re planning an exciting project. Let me help you create a comprehensive plan.',
        'Excellent! This sounds like a great venture. I\'ll help you develop a detailed project strategy.',
        'Fantastic! I\'ll assist you in building a complete project plan for your new initiative.',
        'Wonderful! Let\'s create a strategic roadmap for your project.',
        'Great choice! I\'ll help you plan this project from start to finish.',
        'Outstanding! This is an interesting project. Let me help you create a comprehensive plan.',
        'Brilliant! I\'ll assist you in developing a detailed project strategy.',
        'Amazing! Let\'s build a complete project plan for your new venture.',
        'Superb! I\'ll help you create a strategic approach for your project.',
        'Excellent! This project has great potential. Let me help you plan it thoroughly.'
    ],
    'project.status': [
        'Here\'s your project status.',
        'Current project progress:',
        'Project status overview:'
    ],
    'timeline.query': [
        'Here\'s your project timeline.',
        'Timeline overview:',
        'Project schedule:'
    ],
    'stakeholder.add': [
        'I\'ll add a team member.',
        'Adding the new team member.',
        'Team member added successfully.'
    ],
    
    // Action Planning Response Templates
    'action.ask_objectives': [
        'What are your main objectives for this project?',
        'Could you describe the goals you want to achieve?',
        'What do you hope to accomplish with this project?'
    ],
    'action.ask_budget': [
        'What budget do you have available for this project?',
        'What financial resources are allocated for this work?',
        'What\'s your budget range for this project?'
    ],
    'action.ask_tasks': [
        'What specific tasks or deliverables do you need?',
        'What are the key activities for this project?',
        'What work needs to be completed?'
    ],
    'action.ask_people': [
        'Who will be involved in this project?',
        'What team members or stakeholders need to be included?',
        'Who are the key people for this project?'
    ],
    'action.ask_detailed': [
        'Could you provide more detailed information about this?',
        'I\'d like to understand this better - can you elaborate?',
        'Let me get a comprehensive understanding of your needs.'
    ],
    'action.ask_direct': [
        'What\'s your budget?',
        'When do you need this completed?',
        'Who\'s involved?'
    ],
    'action.ask_balanced': [
        'Tell me about your project requirements.',
        'What are the key details I should know?',
        'Help me understand your project needs.'
    ],
    'action.ask_exploratory': [
        'Let\'s explore this together - what\'s your vision?',
        'I\'d love to understand more about your goals.',
        'Tell me more about what you\'re thinking.'
    ],
    'action.provide_recommendation': [
        'Based on what we\'ve discussed, here are my recommendations.',
        'Your project looks well-defined. Here\'s what I suggest.',
        'Great progress! Here\'s my recommended next steps.'
    ],
    'action.request_clarification': [
        'I want to make sure I understand correctly - could you clarify?',
        'Let me make sure I have this right - can you explain more?',
        'I need a bit more clarity on this - could you elaborate?'
    ],
    'action.continue_planning': [
        'Let\'s continue building your project plan.',
        'We\'re making good progress - let\'s keep going.',
        'Let\'s work on the next part of your project.'
    ],
    'action.escalate_complexity': [
        'This looks like a complex project - let\'s plan it thoroughly.',
        'Given the complexity, we\'ll need a detailed approach.',
        'This requires advanced planning - let\'s break it down systematically.'
    ],
    'action.simplify_approach': [
        'This looks straightforward - let\'s keep it simple.',
        'For this project, we can use a streamlined approach.',
        'Let\'s plan this with a simple, effective strategy.'
    ],
    
    // Gap Detection Response Templates
    'gap.critical_objectives': [
        'Objectives are missing - this is critical and blocks all planning.',
        'Without objectives, we cannot proceed with timeline or budget planning.',
        'Objectives are the foundation - we need to define them first.'
    ],
    'gap.high_priority_budget': [
        'Budget information is missing - this is high priority for planning.',
        'Without budget constraints, we cannot plan resource allocation.',
        'Budget is needed to determine project feasibility and scope.'
    ],
    'gap.medium_tasks': [
        'Tasks and deliverables need to be defined for execution planning.',
        'Without tasks, we cannot create a realistic timeline.',
        'Task definition is needed to understand project scope.'
    ],
    'gap.low_people': [
        'Stakeholder and team information would help with coordination.',
        'Knowing who\'s involved helps with communication planning.',
        'Team structure affects project coordination and success.'
    ],
    'gap.prioritize_multiple': [
        'Multiple gaps detected - let\'s prioritize them systematically.',
        'Several areas need attention - we\'ll address them in order of importance.',
        'Multiple gaps require prioritization based on project impact.'
    ],
    'gap.analyze_dependencies': [
        'Gap dependencies need to be analyzed for proper sequencing.',
        'Some gaps block others - we need to address dependencies first.',
        'Dependency analysis is crucial for effective gap resolution.'
    ],
    'gap.partial_completion': [
        'Some areas are complete while others need attention.',
        'Partial completion - let\'s focus on the remaining gaps.',
        'Mixed completion status - we\'ll address the missing pieces.'
    ],
    'gap.all_complete': [
        'All areas are well-defined - project is ready for execution.',
        'No critical gaps remain - project planning is comprehensive.',
        'Project is fully defined and ready to proceed.'
    ],
    'gap.priority_scoring': [
        'Gap priority scoring based on impact and dependencies.',
        'Prioritizing gaps by criticality and project impact.',
        'Scoring gaps to determine resolution order.'
    ],
    'gap.impact_analysis': [
        'Analyzing gap impact on project success and timeline.',
        'Each gap has different impact levels on project execution.',
        'Impact analysis helps prioritize gap resolution efforts.'
    ],
    'gap.template_analysis': [
        'Analyzing template areas for completeness and gaps.',
        'Template area analysis reveals missing project components.',
        'Systematic analysis of all project template areas.'
    ],
    'gap.reasoning_analysis': [
        'Analyzing reasoning behind each gap and its implications.',
        'Understanding why each gap matters for project success.',
        'Reasoning analysis helps prioritize and resolve gaps effectively.'
    ],
    'gap.resolution_analysis': [
        'Analyzing gap resolution progress and remaining work.',
        'Tracking which gaps have been resolved and which remain.',
        'Resolution analysis shows progress in gap closure.'
    ],
    'gap.evolution_analysis': [
        'Analyzing how gaps evolve and change over time.',
        'Tracking gap evolution and adapting resolution strategies.',
        'Evolution analysis helps anticipate future gap changes.'
    ]
};

// Intent to action mapping
export const intentActionMap = {
    'project.create': 'CREATE_PROJECT',
    'scope.define': 'DEFINE_SCOPE',
    'budget.set': 'SET_BUDGET',
    'timeline.set': 'SET_TIMELINE',
    'tasks.create': 'CREATE_TASKS',
    'tasks.list': 'LIST_TASKS',
    'tasks.complete': 'COMPLETE_TASK',
    'deliverables.define': 'DEFINE_DELIVERABLES',
    'dependencies.define': 'DEFINE_DEPENDENCIES',
    'response.positive': 'CONFIRM',
    'response.negative': 'REJECT',
    'general.clarify': 'CLARIFY',
    'general.help': 'SHOW_HELP',
    'general.thanks': 'ACKNOWLEDGE',
    'project.rename': 'RENAME_PROJECT',
    'project.name_generate': 'GENERATE_PROJECT_NAME',
    'project.status': 'GET_STATUS',
    'timeline.query': 'SHOW_TIMELINE',
    'stakeholder.add': 'ADD_STAKEHOLDER',
    
    // Action Planning Intent Mappings
    'action.ask_objectives': 'ASK_ABOUT_OBJECTIVES',
    'action.ask_budget': 'ASK_ABOUT_BUDGET',
    'action.ask_tasks': 'ASK_ABOUT_TASKS',
    'action.ask_people': 'ASK_ABOUT_PEOPLE',
    'action.ask_detailed': 'ASK_DETAILED_QUESTION',
    'action.ask_direct': 'ASK_DIRECT_QUESTION',
    'action.ask_balanced': 'ASK_BALANCED_QUESTION',
    'action.ask_exploratory': 'ASK_EXPLORATORY_QUESTION',
    'action.provide_recommendation': 'PROVIDE_RECOMMENDATION',
    'action.request_clarification': 'REQUEST_CLARIFICATION',
    'action.continue_planning': 'CONTINUE_PLANNING',
    'action.escalate_complexity': 'ESCALATE_COMPLEXITY',
    'action.simplify_approach': 'SIMPLIFY_APPROACH',
    
    // Gap Detection Intent Mappings
    'gap.critical_objectives': 'CRITICAL_OBJECTIVES_GAP',
    'gap.high_priority_budget': 'HIGH_PRIORITY_BUDGET_GAP',
    'gap.medium_tasks': 'MEDIUM_PRIORITY_TASKS_GAP',
    'gap.low_people': 'LOW_PRIORITY_PEOPLE_GAP',
    'gap.prioritize_multiple': 'PRIORITIZE_MULTIPLE_GAPS',
    'gap.analyze_dependencies': 'ANALYZE_GAP_DEPENDENCIES',
    'gap.partial_completion': 'PARTIAL_COMPLETION_ANALYSIS',
    'gap.all_complete': 'ALL_AREAS_COMPLETE',
    'gap.priority_scoring': 'GAP_PRIORITY_SCORING',
    'gap.impact_analysis': 'GAP_IMPACT_ANALYSIS',
    'gap.template_analysis': 'TEMPLATE_AREA_ANALYSIS',
    'gap.reasoning_analysis': 'GAP_REASONING_ANALYSIS',
    'gap.resolution_analysis': 'GAP_RESOLUTION_ANALYSIS',
    'gap.evolution_analysis': 'GAP_EVOLUTION_ANALYSIS'
};

// Future: Sentiment analysis configuration
export const sentimentAnalysis = {
    enabled: false, // Will be enabled in future versions
    thresholds: {
        positive: 0.6,
        negative: -0.6,
        neutral: 0.2
    }
};

// Future: State response patterns
export const stateResponsePatterns = {
    enabled: false, // Will be enabled in future versions
    patterns: []
};

// Future: State response templates
export const stateResponseTemplates = {
    enabled: false, // Will be enabled in future versions
    templates: {}
};
